### ISSUE TITLE
Playground Preview

### ISSUE THREAD

**Issue by sxzz** [phoenix-ru/fervid#1]
The project is wonderful.

In other to test and check it more conveniently, I'd like to request a playground, like [this one](https://herringtondarkholme.github.io/vue-compiler/).

**Comment by phoenix-ru** [comment]
Thanks for your comment. I would also love to work on a playground, however, it needs WASM bindings first. If you know how to setup wasm target and GitHub pages, your ideas are welcome

As of now, I am working on providing a "preview API" and preparing for crate publishing, so you'd be able to play with its Rust API and maybe build something on top

**Comment by phoenix-ru** [comment]
Publishing `fervid` is currently blocked by incompatibilities introduced in `lightningcss` and a Pull Request being rejected:
https://github.com/parcel-bundler/lightningcss/pull/485

I would have to create a different PR, otherwise CSS transformations for Vue would be unsupported

**Comment by phoenix-ru** [comment]
Deployed to https://phoenix-ru.github.io/fervid/
