### ISSUE TITLE
[Bug Report]: not find napi node binary product

### ISSUE THREAD

**Issue by ErKeLost** [phoenix-ru/fervid#59]
Should include cross-platform build artifacts

![image](https://github.com/user-attachments/assets/91a66335-7658-4d4a-8ee7-5e73f523ae29)

**Comment by phoenix-ru** [comment]
Hi, you're right. The release broke after https://github.com/phoenix-ru/fervid/pull/33

I will change the package json files and republish

**Comment by phoenix-ru** [comment]
Version 0.3.1 is out!

https://www.npmjs.com/package/@fervid/napi-darwin-arm64?activeTab=code
